version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser           # Nome do usuário do banco de dados
      POSTGRES_PASSWORD: mypassword   # Senha do banco de dados
      POSTGRES_DB: alfa-manager-dev   # Nome do banco de dados
    ports:
      - "5432:5432"                   # Porta exposta (5432 é a padrão do PostgreSQL)
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume para persistência dos dados

volumes:
  postgres_data:                      # Volume para persistência dos dados do PostgreSQL
